/**
 * Autogenerated by Avro
 * <p>
 * DO NOT EDIT DIRECTLY
 */
package nlmk.l3.pdm;

@org.apache.avro.specific.AvroGenerated
public enum opEnum implements org.apache.avro.generic.GenericEnumSymbol<opEnum> {
    I, U, D;
    public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"opEnum\",\"namespace\":\"nlmk.l3.pdm\",\"symbols\":[\"I\",\"U\",\"D\"]}");

    public static org.apache.avro.Schema getClassSchema() {
        return SCHEMA$;
    }

    public org.apache.avro.Schema getSchema() {
        return SCHEMA$;
    }
}
