/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package nlmk.l3.pdm;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Pk extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 8762320896145865848L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Pk\",\"namespace\":\"nlmk.l3.pdm\",\"fields\":[{\"name\":\"systemCode\",\"type\":\"string\"},{\"name\":\"directoryId\",\"type\":\"string\"},{\"name\":\"Id\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Pk> ENCODER =
      new BinaryMessageEncoder<Pk>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Pk> DECODER =
      new BinaryMessageDecoder<Pk>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Pk> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Pk> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Pk> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Pk>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Pk to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Pk from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Pk instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Pk fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.CharSequence systemCode;
   private java.lang.CharSequence directoryId;
   private java.lang.CharSequence Id;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Pk() {}

  /**
   * All-args constructor.
   * @param systemCode The new value for systemCode
   * @param directoryId The new value for directoryId
   * @param Id The new value for Id
   */
  public Pk(java.lang.CharSequence systemCode, java.lang.CharSequence directoryId, java.lang.CharSequence Id) {
    this.systemCode = systemCode;
    this.directoryId = directoryId;
    this.Id = Id;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return systemCode;
    case 1: return directoryId;
    case 2: return Id;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: systemCode = (java.lang.CharSequence)value$; break;
    case 1: directoryId = (java.lang.CharSequence)value$; break;
    case 2: Id = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'systemCode' field.
   * @return The value of the 'systemCode' field.
   */
  public java.lang.CharSequence getSystemCode() {
    return systemCode;
  }


  /**
   * Sets the value of the 'systemCode' field.
   * @param value the value to set.
   */
  public void setSystemCode(java.lang.CharSequence value) {
    this.systemCode = value;
  }

  /**
   * Gets the value of the 'directoryId' field.
   * @return The value of the 'directoryId' field.
   */
  public java.lang.CharSequence getDirectoryId() {
    return directoryId;
  }


  /**
   * Sets the value of the 'directoryId' field.
   * @param value the value to set.
   */
  public void setDirectoryId(java.lang.CharSequence value) {
    this.directoryId = value;
  }

  /**
   * Gets the value of the 'Id' field.
   * @return The value of the 'Id' field.
   */
  public java.lang.CharSequence getId() {
    return Id;
  }


  /**
   * Sets the value of the 'Id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.CharSequence value) {
    this.Id = value;
  }

  /**
   * Creates a new Pk RecordBuilder.
   * @return A new Pk RecordBuilder
   */
  public static nlmk.l3.pdm.Pk.Builder newBuilder() {
    return new nlmk.l3.pdm.Pk.Builder();
  }

  /**
   * Creates a new Pk RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Pk RecordBuilder
   */
  public static nlmk.l3.pdm.Pk.Builder newBuilder(nlmk.l3.pdm.Pk.Builder other) {
    if (other == null) {
      return new nlmk.l3.pdm.Pk.Builder();
    } else {
      return new nlmk.l3.pdm.Pk.Builder(other);
    }
  }

  /**
   * Creates a new Pk RecordBuilder by copying an existing Pk instance.
   * @param other The existing instance to copy.
   * @return A new Pk RecordBuilder
   */
  public static nlmk.l3.pdm.Pk.Builder newBuilder(nlmk.l3.pdm.Pk other) {
    if (other == null) {
      return new nlmk.l3.pdm.Pk.Builder();
    } else {
      return new nlmk.l3.pdm.Pk.Builder(other);
    }
  }

  /**
   * RecordBuilder for Pk instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Pk>
    implements org.apache.avro.data.RecordBuilder<Pk> {

    private java.lang.CharSequence systemCode;
    private java.lang.CharSequence directoryId;
    private java.lang.CharSequence Id;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(nlmk.l3.pdm.Pk.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.systemCode)) {
        this.systemCode = data().deepCopy(fields()[0].schema(), other.systemCode);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.directoryId)) {
        this.directoryId = data().deepCopy(fields()[1].schema(), other.directoryId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.Id)) {
        this.Id = data().deepCopy(fields()[2].schema(), other.Id);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing Pk instance
     * @param other The existing instance to copy.
     */
    private Builder(nlmk.l3.pdm.Pk other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.systemCode)) {
        this.systemCode = data().deepCopy(fields()[0].schema(), other.systemCode);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.directoryId)) {
        this.directoryId = data().deepCopy(fields()[1].schema(), other.directoryId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.Id)) {
        this.Id = data().deepCopy(fields()[2].schema(), other.Id);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'systemCode' field.
      * @return The value.
      */
    public java.lang.CharSequence getSystemCode() {
      return systemCode;
    }


    /**
      * Sets the value of the 'systemCode' field.
      * @param value The value of 'systemCode'.
      * @return This builder.
      */
    public nlmk.l3.pdm.Pk.Builder setSystemCode(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.systemCode = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'systemCode' field has been set.
      * @return True if the 'systemCode' field has been set, false otherwise.
      */
    public boolean hasSystemCode() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'systemCode' field.
      * @return This builder.
      */
    public nlmk.l3.pdm.Pk.Builder clearSystemCode() {
      systemCode = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'directoryId' field.
      * @return The value.
      */
    public java.lang.CharSequence getDirectoryId() {
      return directoryId;
    }


    /**
      * Sets the value of the 'directoryId' field.
      * @param value The value of 'directoryId'.
      * @return This builder.
      */
    public nlmk.l3.pdm.Pk.Builder setDirectoryId(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.directoryId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'directoryId' field has been set.
      * @return True if the 'directoryId' field has been set, false otherwise.
      */
    public boolean hasDirectoryId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'directoryId' field.
      * @return This builder.
      */
    public nlmk.l3.pdm.Pk.Builder clearDirectoryId() {
      directoryId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'Id' field.
      * @return The value.
      */
    public java.lang.CharSequence getId() {
      return Id;
    }


    /**
      * Sets the value of the 'Id' field.
      * @param value The value of 'Id'.
      * @return This builder.
      */
    public nlmk.l3.pdm.Pk.Builder setId(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.Id = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'Id' field has been set.
      * @return True if the 'Id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'Id' field.
      * @return This builder.
      */
    public nlmk.l3.pdm.Pk.Builder clearId() {
      Id = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Pk build() {
      try {
        Pk record = new Pk();
        record.systemCode = fieldSetFlags()[0] ? this.systemCode : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.directoryId = fieldSetFlags()[1] ? this.directoryId : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.Id = fieldSetFlags()[2] ? this.Id : (java.lang.CharSequence) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Pk>
    WRITER$ = (org.apache.avro.io.DatumWriter<Pk>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Pk>
    READER$ = (org.apache.avro.io.DatumReader<Pk>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.systemCode);

    out.writeString(this.directoryId);

    out.writeString(this.Id);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.systemCode = in.readString(this.systemCode instanceof Utf8 ? (Utf8)this.systemCode : null);

      this.directoryId = in.readString(this.directoryId instanceof Utf8 ? (Utf8)this.directoryId : null);

      this.Id = in.readString(this.Id instanceof Utf8 ? (Utf8)this.Id : null);

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.systemCode = in.readString(this.systemCode instanceof Utf8 ? (Utf8)this.systemCode : null);
          break;

        case 1:
          this.directoryId = in.readString(this.directoryId instanceof Utf8 ? (Utf8)this.directoryId : null);
          break;

        case 2:
          this.Id = in.readString(this.Id instanceof Utf8 ? (Utf8)this.Id : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










