/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package nlmk.l3.pdm;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Spec extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -371951307473448421L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Spec\",\"namespace\":\"nlmk.l3.pdm\",\"fields\":[{\"name\":\"specCode\",\"type\":\"int\"},{\"name\":\"specName\",\"type\":\"string\"},{\"name\":\"specTypeCode\",\"type\":\"int\"},{\"name\":\"specValue\",\"type\":\"string\"},{\"name\":\"specMeasure\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Spec> ENCODER =
      new BinaryMessageEncoder<Spec>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Spec> DECODER =
      new BinaryMessageDecoder<Spec>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Spec> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Spec> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Spec> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Spec>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Spec to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Spec from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Spec instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Spec fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private int specCode;
   private java.lang.CharSequence specName;
   private int specTypeCode;
   private java.lang.CharSequence specValue;
   private java.lang.CharSequence specMeasure;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Spec() {}

  /**
   * All-args constructor.
   * @param specCode The new value for specCode
   * @param specName The new value for specName
   * @param specTypeCode The new value for specTypeCode
   * @param specValue The new value for specValue
   * @param specMeasure The new value for specMeasure
   */
  public Spec(java.lang.Integer specCode, java.lang.CharSequence specName, java.lang.Integer specTypeCode, java.lang.CharSequence specValue, java.lang.CharSequence specMeasure) {
    this.specCode = specCode;
    this.specName = specName;
    this.specTypeCode = specTypeCode;
    this.specValue = specValue;
    this.specMeasure = specMeasure;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return specCode;
    case 1: return specName;
    case 2: return specTypeCode;
    case 3: return specValue;
    case 4: return specMeasure;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: specCode = (java.lang.Integer)value$; break;
    case 1: specName = (java.lang.CharSequence)value$; break;
    case 2: specTypeCode = (java.lang.Integer)value$; break;
    case 3: specValue = (java.lang.CharSequence)value$; break;
    case 4: specMeasure = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'specCode' field.
   * @return The value of the 'specCode' field.
   */
  public int getSpecCode() {
    return specCode;
  }


  /**
   * Sets the value of the 'specCode' field.
   * @param value the value to set.
   */
  public void setSpecCode(int value) {
    this.specCode = value;
  }

  /**
   * Gets the value of the 'specName' field.
   * @return The value of the 'specName' field.
   */
  public java.lang.CharSequence getSpecName() {
    return specName;
  }


  /**
   * Sets the value of the 'specName' field.
   * @param value the value to set.
   */
  public void setSpecName(java.lang.CharSequence value) {
    this.specName = value;
  }

  /**
   * Gets the value of the 'specTypeCode' field.
   * @return The value of the 'specTypeCode' field.
   */
  public int getSpecTypeCode() {
    return specTypeCode;
  }


  /**
   * Sets the value of the 'specTypeCode' field.
   * @param value the value to set.
   */
  public void setSpecTypeCode(int value) {
    this.specTypeCode = value;
  }

  /**
   * Gets the value of the 'specValue' field.
   * @return The value of the 'specValue' field.
   */
  public java.lang.CharSequence getSpecValue() {
    return specValue;
  }


  /**
   * Sets the value of the 'specValue' field.
   * @param value the value to set.
   */
  public void setSpecValue(java.lang.CharSequence value) {
    this.specValue = value;
  }

  /**
   * Gets the value of the 'specMeasure' field.
   * @return The value of the 'specMeasure' field.
   */
  public java.lang.CharSequence getSpecMeasure() {
    return specMeasure;
  }


  /**
   * Sets the value of the 'specMeasure' field.
   * @param value the value to set.
   */
  public void setSpecMeasure(java.lang.CharSequence value) {
    this.specMeasure = value;
  }

  /**
   * Creates a new Spec RecordBuilder.
   * @return A new Spec RecordBuilder
   */
  public static nlmk.l3.pdm.Spec.Builder newBuilder() {
    return new nlmk.l3.pdm.Spec.Builder();
  }

  /**
   * Creates a new Spec RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Spec RecordBuilder
   */
  public static nlmk.l3.pdm.Spec.Builder newBuilder(nlmk.l3.pdm.Spec.Builder other) {
    if (other == null) {
      return new nlmk.l3.pdm.Spec.Builder();
    } else {
      return new nlmk.l3.pdm.Spec.Builder(other);
    }
  }

  /**
   * Creates a new Spec RecordBuilder by copying an existing Spec instance.
   * @param other The existing instance to copy.
   * @return A new Spec RecordBuilder
   */
  public static nlmk.l3.pdm.Spec.Builder newBuilder(nlmk.l3.pdm.Spec other) {
    if (other == null) {
      return new nlmk.l3.pdm.Spec.Builder();
    } else {
      return new nlmk.l3.pdm.Spec.Builder(other);
    }
  }

  /**
   * RecordBuilder for Spec instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Spec>
    implements org.apache.avro.data.RecordBuilder<Spec> {

    private int specCode;
    private java.lang.CharSequence specName;
    private int specTypeCode;
    private java.lang.CharSequence specValue;
    private java.lang.CharSequence specMeasure;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(nlmk.l3.pdm.Spec.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.specCode)) {
        this.specCode = data().deepCopy(fields()[0].schema(), other.specCode);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.specName)) {
        this.specName = data().deepCopy(fields()[1].schema(), other.specName);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.specTypeCode)) {
        this.specTypeCode = data().deepCopy(fields()[2].schema(), other.specTypeCode);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.specValue)) {
        this.specValue = data().deepCopy(fields()[3].schema(), other.specValue);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.specMeasure)) {
        this.specMeasure = data().deepCopy(fields()[4].schema(), other.specMeasure);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
    }

    /**
     * Creates a Builder by copying an existing Spec instance
     * @param other The existing instance to copy.
     */
    private Builder(nlmk.l3.pdm.Spec other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.specCode)) {
        this.specCode = data().deepCopy(fields()[0].schema(), other.specCode);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.specName)) {
        this.specName = data().deepCopy(fields()[1].schema(), other.specName);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.specTypeCode)) {
        this.specTypeCode = data().deepCopy(fields()[2].schema(), other.specTypeCode);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.specValue)) {
        this.specValue = data().deepCopy(fields()[3].schema(), other.specValue);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.specMeasure)) {
        this.specMeasure = data().deepCopy(fields()[4].schema(), other.specMeasure);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'specCode' field.
      * @return The value.
      */
    public int getSpecCode() {
      return specCode;
    }


    /**
      * Sets the value of the 'specCode' field.
      * @param value The value of 'specCode'.
      * @return This builder.
      */
    public nlmk.l3.pdm.Spec.Builder setSpecCode(int value) {
      validate(fields()[0], value);
      this.specCode = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'specCode' field has been set.
      * @return True if the 'specCode' field has been set, false otherwise.
      */
    public boolean hasSpecCode() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'specCode' field.
      * @return This builder.
      */
    public nlmk.l3.pdm.Spec.Builder clearSpecCode() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'specName' field.
      * @return The value.
      */
    public java.lang.CharSequence getSpecName() {
      return specName;
    }


    /**
      * Sets the value of the 'specName' field.
      * @param value The value of 'specName'.
      * @return This builder.
      */
    public nlmk.l3.pdm.Spec.Builder setSpecName(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.specName = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'specName' field has been set.
      * @return True if the 'specName' field has been set, false otherwise.
      */
    public boolean hasSpecName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'specName' field.
      * @return This builder.
      */
    public nlmk.l3.pdm.Spec.Builder clearSpecName() {
      specName = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'specTypeCode' field.
      * @return The value.
      */
    public int getSpecTypeCode() {
      return specTypeCode;
    }


    /**
      * Sets the value of the 'specTypeCode' field.
      * @param value The value of 'specTypeCode'.
      * @return This builder.
      */
    public nlmk.l3.pdm.Spec.Builder setSpecTypeCode(int value) {
      validate(fields()[2], value);
      this.specTypeCode = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'specTypeCode' field has been set.
      * @return True if the 'specTypeCode' field has been set, false otherwise.
      */
    public boolean hasSpecTypeCode() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'specTypeCode' field.
      * @return This builder.
      */
    public nlmk.l3.pdm.Spec.Builder clearSpecTypeCode() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'specValue' field.
      * @return The value.
      */
    public java.lang.CharSequence getSpecValue() {
      return specValue;
    }


    /**
      * Sets the value of the 'specValue' field.
      * @param value The value of 'specValue'.
      * @return This builder.
      */
    public nlmk.l3.pdm.Spec.Builder setSpecValue(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.specValue = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'specValue' field has been set.
      * @return True if the 'specValue' field has been set, false otherwise.
      */
    public boolean hasSpecValue() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'specValue' field.
      * @return This builder.
      */
    public nlmk.l3.pdm.Spec.Builder clearSpecValue() {
      specValue = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'specMeasure' field.
      * @return The value.
      */
    public java.lang.CharSequence getSpecMeasure() {
      return specMeasure;
    }


    /**
      * Sets the value of the 'specMeasure' field.
      * @param value The value of 'specMeasure'.
      * @return This builder.
      */
    public nlmk.l3.pdm.Spec.Builder setSpecMeasure(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.specMeasure = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'specMeasure' field has been set.
      * @return True if the 'specMeasure' field has been set, false otherwise.
      */
    public boolean hasSpecMeasure() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'specMeasure' field.
      * @return This builder.
      */
    public nlmk.l3.pdm.Spec.Builder clearSpecMeasure() {
      specMeasure = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Spec build() {
      try {
        Spec record = new Spec();
        record.specCode = fieldSetFlags()[0] ? this.specCode : (java.lang.Integer) defaultValue(fields()[0]);
        record.specName = fieldSetFlags()[1] ? this.specName : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.specTypeCode = fieldSetFlags()[2] ? this.specTypeCode : (java.lang.Integer) defaultValue(fields()[2]);
        record.specValue = fieldSetFlags()[3] ? this.specValue : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.specMeasure = fieldSetFlags()[4] ? this.specMeasure : (java.lang.CharSequence) defaultValue(fields()[4]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Spec>
    WRITER$ = (org.apache.avro.io.DatumWriter<Spec>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Spec>
    READER$ = (org.apache.avro.io.DatumReader<Spec>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeInt(this.specCode);

    out.writeString(this.specName);

    out.writeInt(this.specTypeCode);

    out.writeString(this.specValue);

    out.writeString(this.specMeasure);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.specCode = in.readInt();

      this.specName = in.readString(this.specName instanceof Utf8 ? (Utf8)this.specName : null);

      this.specTypeCode = in.readInt();

      this.specValue = in.readString(this.specValue instanceof Utf8 ? (Utf8)this.specValue : null);

      this.specMeasure = in.readString(this.specMeasure instanceof Utf8 ? (Utf8)this.specMeasure : null);

    } else {
      for (int i = 0; i < 5; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.specCode = in.readInt();
          break;

        case 1:
          this.specName = in.readString(this.specName instanceof Utf8 ? (Utf8)this.specName : null);
          break;

        case 2:
          this.specTypeCode = in.readInt();
          break;

        case 3:
          this.specValue = in.readString(this.specValue instanceof Utf8 ? (Utf8)this.specValue : null);
          break;

        case 4:
          this.specMeasure = in.readString(this.specMeasure instanceof Utf8 ? (Utf8)this.specMeasure : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










